#Messages
Messages:
   prefix: "&9&lDevolution &8> &f"
   lobbynotset: "Lobby is not set"
golem-weapon-name: "GolemWeapon"
blaze-weapon-name: "BlazeWeapon"
spider-weapon-name: "SpiderWeapon"
creeper-weapon-name: "CreeperWeapon"
slime-weapon-name: "SlimeWeapon"
chicken-weapon-name: "ChickenWeapon"